#env: "prod" #local, dev, prod
#storage_path: "./storage/storage.db"
#http_server:
#  address: "localhost:8080"
#  timeout: 4s
#  idle_timeout: 60s
#
#db_user: root
#db_password: pass
#db_host: mysql-8.0
#db_port: 3306
#db_name: test_new_logic
#parse_time: true


env: "prod" #local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s

db_user: Kuznecov_av
db_password: BV02y0Xer72a
db_host: 192.168.2.10
db_port: 3306
db_name: demetra_test
parse_time: true